# Generated by Django 5.2 on 2025-04-26 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aerotech', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='empleado_asignado',
            new_name='empleado',
        ),
    ]
