# Generated by Django 5.2 on 2025-04-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aerotech', '0002_rename_empleado_asignado_ticket_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='equipo',
        ),
        migrations.AddField(
            model_name='ticket',
            name='equipos',
            field=models.ManyToManyField(to='Aerotech.equipo'),
        ),
    ]
