# Generated by Django 5.1.7 on 2025-05-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aerotech', '0003_remove_ticket_equipo_ticket_equipos'),
    ]

    operations = [
       migrations.AddField(
            model_name='empleado',
            name='username',
            field=models.CharField(max_length=150, unique=False, null=True, blank=True),
        ),
    ]
