# Generated by Django 5.1.7 on 2025-05-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aerotech', '0005_alter_empleado_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='username',
        ),
    ]
