# Generated by Django 5.1.7 on 2025-05-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aerotech', '0006_remove_empleado_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
