# Generated by Django 5.1.7 on 2025-06-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aerotech', '0007_empleado_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='proveedor_nombre',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='proveedor_telefono',
        ),
        migrations.AddField(
            model_name='empleado',
            name='departamento',
            field=models.CharField(choices=[('1', 'Dirección'), ('2', 'Mantenimiento'), ('3', 'Logística')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipo',
            name='marca',
            field=models.CharField(choices=[('1', 'Ikertronic'), ('2', 'JonAndertech')], max_length=50),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(choices=[('1', 'aaaaaa000'), ('2', 'aaaaaaa111'), ('3', 'aaaaaaa999'), ('4', 'aaaaaaa888')], max_length=50),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(choices=[('1', 'Deshumidificador de Aire'), ('2', 'Depuradora'), ('3', 'Aire Acondicionado')], max_length=50),
        ),
        migrations.AddField(
            model_name='equipo',
            name='proveedores',
            field=models.ManyToManyField(related_name='equipos', to='Aerotech.proveedor'),
        ),
    ]
