# Generated by Django 5.2 on 2025-06-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aerotech', '0008_proveedor_remove_equipo_proveedor_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='departamento',
            field=models.CharField(choices=[('Dirección', 'Dirección'), ('Mantenimiento', 'Mantenimiento'), ('Logística', 'Logística')], max_length=50),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='marca',
            field=models.CharField(choices=[('Ikertronic', 'Ikertronic'), ('JonAndertech', 'JonAndertech')], max_length=50),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(choices=[('aaaaaa000', 'aaaaaa000'), ('aaaaaaa111', 'aaaaaaa111'), ('aaaaaaa999', 'aaaaaaa999'), ('aaaaaaa888', 'aaaaaaa888')], max_length=50),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='proveedores',
            field=models.ManyToManyField(related_name='proveedores', to='Aerotech.proveedor'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(choices=[('Deshumidificador de Aire', 'Deshumidificador de Aire'), ('Depuradora', 'Depuradora'), ('Aire Acondicionado', 'Aire Acondicionado')], max_length=50),
        ),
    ]
